config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :decisions do
    member do
      get 'decide'
    end
    resources :options, only: [:new, :create] do
      member do
        get 'ask'
        get 'score'
      end
    end
  end
  resources :options, only: [:show, :destroy] do
    resources :arguments, only: [:new, :create]
  end
  resources :arguments, only: [:show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/argument.rb
class Argument < ApplicationRecord
  belongs_to :option
  validates_presence_of :argument_name, :score

  def emoji
    case score
    when 3 then '😀'
    when 2 then '🙂'
    when 1 then '🙁'
    when 0 then '😢'
    else
      '❓'
    end
  end
end

app/models/decision.rb
class Decision < ApplicationRecord
  belongs_to :user
  has_many :options, dependent: :destroy
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :decision
  has_many :arguments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :decisions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
end

app/controllers/arguments_controller.rb
class ArgumentsController < ApplicationController
  # def index
  #   @arguments = Argument.all
  # end

  def new
    @argument = Argument.new
    @option = Option.find(params[:option_id])
  end

  def create
    @option = Option.find(params[:option_id])
    @argument = Argument.new(argument_params)
    @argument.option = @option
    if @argument.save
      redirect_to option_path(@option)
    else
      render 'options/show', status: :unprocessable_entity
    end
  end

  def destroy
    @argument = Argument.find(params[:id])
    @argument.destroy
    redirect_to decisions_path(@decision), status: :see_other
  end

  private

  def argument_params
    params.require(:argument).permit(:argument_name, :score)
  end
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  def index
    @decisions = Decision.all
  end

  def show
    @decision = Decision.find(params[:id])
    @option = Option.new
  end

  def new
    @decision = Decision.new
  end

  def create
    @decision = Decision.new(decision_params)
    @decision.user_id = current_user.id
    if @decision.save
      redirect_to decision_path(@decision)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @decision = Decision.find(params[:id])
    @decision.destroy
    redirect_to decisions_path, status: :see_other
  end

  def decide
    @decision = Decision.find(params[:id])
    @options = @decision.options.order(score: :desc)
    @winner = @options.first
    @allscores = @decision.options.sum(:score).to_f
  end

  private

  def decision_params
    params.require(:decision).permit(:decision_name)
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  # def index
  # @options = Option.all
  # end

  def new
    @decision = Decision.find(params[:decision_id])
    @option = Option.new(params[:id])
  end

  def create
    @decision = Decision.find(params[:decision_id])
    @option = Option.new(option_params)
    @option.decision = @decision
    if @option.save
      respond_to do |format|
        format.html { redirect_to decision_path(@decision) }
        format.text { render partial: "decisions/option", locals: { option: @option }, formats: [:html] }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @option = Option.find(params[:id])
    @argument = Argument.new
    @options = @option.decision.options.order(:id)
    next_index = @options.index(@option) + 1
    @next_option = @options[next_index]
  end

  def destroy
    @option = Option.find(params[:id])
    @decision = @option.decision
    @option.destroy
    redirect_to decision_path(@decision), status: :see_other
  end

  def ask
    @decision = Decision.find(params[:decision_id])
    @option = Option.find(params[:id])
    @options = Option.where(decision: @decision).where.not(id: @option)
  end

  def score
    @decision = Decision.find(params[:decision_id])
    @options = @decision.options.order(:id)
    @option = Option.find(params[:id])
    total = 0
    scores = params.select { |param| param.include?('argument') }
    scores.each_value { |score| total += score.to_i }
    @option.arguments.each { |argument| total += argument.score || 0 }
    @option.score = total
    @option.save
    next_index = @options.index(@option) + 1
    if @options.length > next_index
      next_option = @options[next_index]
      redirect_to ask_decision_option_path(@decision, next_option)
    else
      redirect_to decide_decision_path(@decision)
    end
  end

  private

  def option_params
    params.require(:option).permit(:option_name)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/arguments/_form.html.erb
<%= simple_form_for [option, argument] do |f| %>
  <%= f.input :argument_name %>
  <%= link_to "Show Argumennt", "#", class: "btn btn-primary" %>
  <%= f.submit "Submit argument", class: "btn btn-primary" %>
<% end %>

app/views/arguments/new.html.erb
render 'form', option: @option, argument: @argument

app/views/decisions/_option.html.erb
<div class="style-card">
    <p> <%= option.option_name %> </p>
</div>

app/views/decisions/decide.html.erb
<div class="decide-page">
  <div class="best-decision">
    <h1>Tom says:</h1>
    <p>The best option for<br><strong><%= @decision.decision_name %></strong><br>based on your input is ... </p>
  </div>

  <div class="decide">
    <%# <div class="tom-says"> %>
      <p class="party-face">🥳</p>
      <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
      <lottie-player src="https://assets3.lottiefiles.com/packages/lf20_wys2rrr6.json"  background="transparent"  speed="0.50"  style="width: 100%; height: 400px; top: -180px;"  autoplay class="confetti"></lottie-player>
      <p class="winner"><%= @winner.option_name %></p>
    <%# </div> %>

    <div class="mytable p-3">
      <% @options.each_with_index do | option, index | %>
        <div class="table-row">
          <h3 class="table-item"><%= index + 1 %></h3>
          <h3 class="table-item"><%= option.option_name %></h3>
          <h3 class="table-item"></h3>
          <h3 class="table-item"><%= ((option.score / @allscores) * 100).round(1) %>%</h3>
        </div>
        <%# pros and cons were here %>
      <% end %>
    </div>
    <div class="buttons-on-decide">
      <p class="button-decide"><%= link_to "View all my decisions", decisions_path %> </p>
      <p class="not-button-decide">Share this decision</p>
      <br>
      <br>
      <p class="button-decide-delete"><%= link_to 'Delete Decision', decision_path(@decision), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'delete-button text-danger' %></small></p>
      <%# <button type="button" class="btn btn-outline-success">Congratulations</button> %>
    </div>
  </div>
</div>

app/views/decisions/index.html.erb
  <div class="step-info">
    <p class="step-choices">Review your previous decisions. <br></p>
    <p>Click on one to see more.</p>
  </div>

  <div class="add-decision">
    <div class="decision" onclick="this.querySelector('a').click(); return true;">
      <% @decisions.reverse_each do |decision| %>
      <div class="decisions-container">
        <div class="decision-style-card">
          <p><%= link_to decision.decision_name, decide_decision_path(decision) %></p>
        </div>
      </div>
      <% end %>
    </div>
  </div>

<%# decide_decision_path(@decision)
http://localhost:3000/decisions/18/decide %>

app/views/decisions/new.html.erb
<div class="decision-page">
  <div class="decision-text-block">
    <p class="decision-title">
    What is<br>going on? <br></p>
    <p class="decision-text">Name the desicion that<br>needs to be made.</p>
  </div>

  <div class="create-decision">
    <div class="create-form">
    <%= simple_form_for [@decision] do |f| %>
      <%= f.input :decision_name, label: false, input_html: {placeholder: "Decision name"}%>
      <%= f.submit "Create new decision", class: "add-button btn btn-primary" %>
    <% end %>
    </div>
  </div>
</div>

app/views/decisions/show.html.erb
<div class="step-options">
  <h2>Step 1 <br>Options</h2>
  <p>What are you deciding between? Please add two<br>or more options. </p>
</div>

<div class="option" >
  <div class="create-option">
    <div class="options">
      <% @decision.options.each do |option| %>
      <%= render "option", option: option %>
      <% end %>
    </div>
  <%= simple_form_for [@decision, @option] do |f| %>
    <%= f.input :option_name, label: false, class: "input-field", input_html: {placeholder: "Your option"} %>
    <div id="option-input">
      <%= f.submit "Add option", class: "add-button btn btn-primary" %>
    </div>
  <% end %>
</div>
  </div>
</div>
<div style="height: 80px">
</div>
<footer>
<div class="buttons">
    <p class="show-buttons"><%= link_to 'Back', new_decision_path %></small></p>
  <% if @decision.options.count > 1 %>
    <p class="show-buttons"><%= link_to 'Next', option_path(@decision.options.first) %></small></p>
  <% end %>
</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="<%= meta_description %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <%= favicon_link_tag asset_path('ask_tom_logo.png') %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/options/ask.html.erb
<div class="step-3">
  <h2>Step 3 <br>
  Self-Reflection</h2>
  <br>
  <p>Compare all Pros & Cons
  between your options.</p>
</div>

<div class="decisions">
  <div class="question-list">
    <form action='/decisions/<%= @decision.id %>/options/<%= @option.id %>/score'>
        <% @options.each do |option| %>
          <% option.arguments.each do |argument| %>
            <div class="block">
              <p>Does <strong><%= @option.option_name %></strong> result in <strong><%= argument.argument_name %></strong>&nbsp;?</p>
             <div class="d-flex justify-content-around">
                <div class="tag-item">
                  <input class="tag-selector" type="radio" id="argument<%= argument.id %>-yes" name="argument<%= argument.id %>" value="2">
                  <label for="argument<%= argument.id %>-yes"> Yes </label><br>
                </div>
                <div class="tag-item">
                  <input class="tag-selector" type="radio" id="argument<%= argument.id %>-maybe" name="argument<%= argument.id %>" value="1">
                  <label for="argument<%= argument.id %>-maybe"> Maybe </label><br>
                </div>
                <div class="tag-item">
                  <input class="tag-selector" type="radio" id="argument<%= argument.id %>-no" name="argument<%= argument.id %>" value="0">
                  <label for="argument<%= argument.id %>-no"> No </label><br>
                </div>
             </div>
            </div>
          <% end %>
        <% end %>
        <div style="height: 80px">
        </div>
      <footer>
        <div class="buttons">
          <p class="show-buttons"><%= link_to 'Back', option_path %></small></p>
          <input type="submit" value="Next" class="next-button">
        </div>
      </footer>
    </form>
  </div>
</div>

app/views/options/new.html.erb
<div class = "form container mb-3">
<%= simple_form_for [@decision, @option] do |f| %>
  <%= f.input :option_name %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>
</div>

app/views/options/show.html.erb
<div class="step-2">
  <h2>Step 2
  <br>Pros & Cons</h2>
  <br>
  <p>What are positive or negative aspects about <strong><%= @option.option_name %></strong> and how does it make you feel?</p>
</div>

<div class="container">
  <div class="content">
    <div class="input">
      <% @option.arguments.each do |argument| %>
        <ul style='padding: 0'>
          <li><%= argument.argument_name %> <%= argument.emoji %></li>
        </ul>
      <% end %>
    </div>

    <div class="" data-controller="mood">
      <div class="w-100 arguments-field">
        <%= simple_form_for [@option, @argument], html: { data: {option_target: "form", action: "submit->option#create"}} do |f| %>
        <%= f.input :argument_name, label: false,class: "w-100", input_html: {class: "flex-fill w-100", placeholder: "argument"} %>
          <%= f.input :score, as: :hidden, label: false, input_html: { data: { mood_target: 'scoreInput'} } %>
          <div class="d-flex justify-content-around mood-buttons">
            <span class="mood-button" data-action="click->mood#select" data-mood-target='emoji' data-score-value='0'>😢</span>
            <span class="mood-button" data-action="click->mood#select" data-mood-target='emoji' data-score-value='1'>🙁</span>
            <span class="mood-button" data-action="click->mood#select" data-mood-target='emoji' data-score-value='2'>🙂</span>
            <span class="mood-button" data-action="click->mood#select" data-mood-target='emoji' data-score-value='3'>😀</span>
          </div>
          <div id="input-id">
        <%= f.submit "Add argument", class: "add-argument-button btn btn-primary w-100" %>
          </div>
        <% end %>
      </div>
    </div>
</div>
<div style="height: 80px">
</div>
<footer>
  <div class="buttons">
    <p class="show-buttons"><%= link_to 'Back', :back %></small></p>
    <%# <p class="show-buttons"><%= link_to 'Delete Option', option_path(@option), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'delete-button text-danger' %><%#</small></p> %>
    <%# <p class="show-buttons"><%= link_to 'Next', option_path(@option) %><%#</small></p> %>
    <% if @next_option %>
      <p class="show-buttons"><%= link_to 'Next', option_path(@next_option)%></small></p>
    <% else %>
      <p class="show-buttons"><%= link_to 'Next', ask_decision_option_path(@option.decision, @options.first) %></small></p>
    <% end %>
  </div>
</footer>

app/views/pages/home.html.erb
<div class="welcome-block">
  <h1 class="welcome-text">Better decisions.<br>Just 3 steps away.</h1>
  <div class="ask-button">
    <%= link_to "Ask Tom", new_decision_path %>
  </div>
</div>

<div class="explanation-style">
  <div class="explanation">
    <div class="step1">
      <p class="steps">Step 1
      <br> Options </p>
      <p> What are you deciding between? </p>
      <br>
      <br>
    </div>

    <div class="step2">
      <p class="steps">Step 2
      <br> Pros & Cons</p>
      <p> What is positive & negative?
      </p>
      <br>
      <br>
    </div>

    <div class="step3">
      <p class="steps">Step 3
      <br>Self-Reflection </p>
      <p> Compare your options.
      </p>
      <br>
      <br>
    </div>

    <div class="start-button">
    <%= link_to "Let’s Start!", new_decision_path %>
      <%# <a href="#">Let’s Start!</a> %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="burger-menu">
  <div class="logo">
  <%= image_tag "ask_tom_logo.png" %>
  </div>
  <input id="menu-toggle" type="checkbox" />
  <label class="menu-btn" for="menu-toggle">
    <span></span>
  </label>

  <ul class="menubox">
          <% if user_signed_in? %>
          <li class="menuitem" onclick="this.querySelector('a').click(); return true;"> <%= link_to "My decisions", decisions_path %> </li>
          <li class="menuitem" onclick="this.querySelector('a').click(); return true;"> <%= link_to "New decision", new_decision_path %> </li>
          <li class="menuitem" onclick="this.querySelector('a').click(); return true;"> <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete} %> </li>
          <% else %>
          <li class="menuitem" onclick="this.querySelector('a').click(); return true;"> <%= link_to "Login", new_user_session_path %> </li>
          <% end %>
  </ul>
</div>